name: black
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install poetry
        run: |
          python -m pip install poetry==1.4.2
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Checking code
        run: |
          black --check --verbose .
