name: black
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Set up project with poetry
        uses: knowsuchagency/poetry-install@v1
      - name: Activating virtual environment
        uses: syphar/restore-virtualenv@v1
      - name: Checking code
        run: |
          black --check --verbose .
