name: black
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Set up project with poetry
        uses: knowsuchagency/poetry-install@v1
      - name: Installing dependencies
        run: |
          poetry install
      - name: Checking code
        run: |
          black --check --verbose .
